#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(HERE, "../..");

export class HeadroomError extends Error {}
function fail(msg) {
	throw new HeadroomError(msg);
}
function loud(msg) {
	process.stderr.write(`headroom: ${msg}\n`);
}

export function computeMedian(scores) {
	const valid = scores.filter((s) => typeof s === "number");
	if (valid.length === 0) return null;
	const sorted = [...valid].sort((a, b) => a - b);
	const mid = Math.floor(sorted.length / 2);
	if (sorted.length % 2 === 0) {
		return (sorted[mid - 1] + sorted[mid]) / 2;
	}
	return sorted[mid];
}

export function computeDecoyRate(diagnoses) {
	const valid = diagnoses.filter((d) => d !== null);
	if (valid.length === 0) return null;
	const falls = valid.filter(
		(d) => d.axes && d.axes.false_leads === true,
	).length;
	return `${falls}/${valid.length}`;
}

export function evaluateVerdict({
	mitigationMedian,
	decoyRate,
	mode,
	threshold,
}) {
	if (mode === "decoy-rate") {
		if (decoyRate === null) {
			return { verdict: "DISQUALIFIED", reason: "no diagnosis available" };
		}
		if (decoyRate.startsWith("0/")) {
			return {
				verdict: "DISQUALIFIED",
				reason: `rate ${decoyRate} (baseline never falls for the decoy)`,
			};
		}
		return { verdict: "QUALIFIED", reason: `rate ${decoyRate}` };
	} else {
		if (mitigationMedian === null) {
			return { verdict: "ERROR", reason: "insufficient valid runs" };
		}
		if (mitigationMedian >= threshold) {
			return {
				verdict: "DISQUALIFIED",
				reason: `mitigation median ${mitigationMedian} >= threshold ${threshold}`,
			};
		}
		return {
			verdict: "QUALIFIED",
			reason: `mitigation median ${mitigationMedian} < threshold ${threshold}`,
		};
	}
}

export function generateHeadroomMd({
	date,
	driver,
	judgeModel,
	threshold,
	mode,
	verdict,
	reason,
	rows,
	mitigationMedian,
	diagnosisMedian,
	decoyRate,
}) {
	const lines = [
		"# Baseline Headroom Qualification",
		"",
		`**${verdict}** — ${reason}`,
		"",
		`**Date**: ${date}`,
		`**Driver**: ${driver || "default"}`,
		`**Judge Model**: ${judgeModel || "none"}`,
		`**Threshold**: ${threshold}`,
		`**Mode**: ${mode}`,
		"",
		"| Run ID | Mitigation Score | Verdict | Diagnosis Score | False Leads |",
		"|---|---|---|---|---|",
	];
	for (const row of rows) {
		const diag = row.diagnosisScore != null ? row.diagnosisScore : "—";
		const fl = row.falseLeads != null ? row.falseLeads : "—";
		const status = row.failed ? "run_failed" : row.verdict || "—";
		const mScore = row.failed ? "—" : row.mitigationScore;
		lines.push(`| ${row.runId} | ${mScore} | ${status} | ${diag} | ${fl} |`);
	}
	lines.push("");
	lines.push(
		`**Mitigation Median**: ${mitigationMedian !== null ? mitigationMedian : "—"}`,
	);
	lines.push(
		`**Diagnosis Median**: ${diagnosisMedian !== null ? diagnosisMedian : "—"}`,
	);
	lines.push(
		`**Falls-for-decoy Rate**: ${decoyRate !== null ? decoyRate : "—"}`,
	);
	lines.push("");
	lines.push("*(Generated by `tools/headroom` for #64)*");
	lines.push("");
	return lines.join("\n");
}

export function findRecordAndDiagnosis(useCase, scenarioId, runId) {
	const useCaseDir = resolve(REPO_ROOT, "use-cases", useCase);
	const scenarioDir = join(useCaseDir, "scenarios", scenarioId);
	const prunedRecordPath = join(scenarioDir, "records", `${runId}.json`);

	let record = null;
	let recordPathFound = null;

	if (existsSync(prunedRecordPath)) {
		try {
			record = JSON.parse(readFileSync(prunedRecordPath, "utf8"));
			recordPathFound = prunedRecordPath;
		} catch {}
	}

	let runDirFound = null;
	if (!record) {
		const stacksDir = join(useCaseDir, "stacks");
		if (existsSync(stacksDir)) {
			const stacks = readdirSync(stacksDir, { withFileTypes: true }).filter(
				(d) => d.isDirectory(),
			);
			for (const stack of stacks) {
				const d = join(stacksDir, stack.name, "runs", runId);
				const p = join(d, "record.json");
				if (existsSync(p)) {
					runDirFound = d;
					try {
						record = JSON.parse(readFileSync(p, "utf8"));
						recordPathFound = p;
					} catch {}
					break;
				}
			}
		}
	} else {
		const stacksDir = join(useCaseDir, "stacks");
		if (existsSync(stacksDir)) {
			const stacks = readdirSync(stacksDir, { withFileTypes: true }).filter(
				(d) => d.isDirectory(),
			);
			for (const stack of stacks) {
				const d = join(stacksDir, stack.name, "runs", runId);
				if (existsSync(join(d, "record.json"))) {
					runDirFound = d;
					break;
				}
			}
		}
	}

	let diagnosis = null;
	if (runDirFound) {
		const dp = join(runDirFound, "diagnosis.json");
		if (existsSync(dp)) {
			try {
				diagnosis = JSON.parse(readFileSync(dp, "utf8"));
			} catch {}
		}
	}

	return {
		record,
		recordPath: recordPathFound,
		diagnosis,
		runDir: runDirFound,
	};
}

export function defaultExecutor(
	{ useCase, rid, agentCmd, scenario },
	spawnSyncFn = spawnSync,
) {
	const env = {
		...process.env,
		SCENARIO_ID: basename(resolveScenarioDir(scenario)),
	};
	if (agentCmd) env.AGENT_CMD = agentCmd;

	const res = spawnSyncFn("pnpm", ["forge", "auto", useCase, `id=${rid}`], {
		stdio: "inherit",
		env,
	});
	return res.status;
}

export function runCampaign({
	scenario,
	runs,
	useCase,
	agentCmd,
	idPrefix,
	executor,
}) {
	const runIds = [];
	const failedRunIds = [];
	// Same normalization as scoreSubcommand: `--scenario` may name the directory
	// or its scenario.toml. Without this a .toml path yields SCENARIO_ID
	// "scenario.toml" and run ids like "headroom-scenario.toml-1".
	const scenarioShort = basename(resolveScenarioDir(scenario));

	for (let i = 1; i <= runs; i++) {
		const rid = `${idPrefix}-${scenarioShort}-${i}`;
		runIds.push(rid);
		loud(
			`Running cycle ${i}/${runs} for scenario ${scenarioShort}, run ID ${rid}...`,
		);
		let status;
		try {
			status = executor({ useCase, rid, agentCmd, scenario });
		} catch {
			status = 1;
		}
		if (status !== 0) {
			loud(`Cycle ${i} failed. Recording run_failed.`);
			failedRunIds.push(rid);
		}
	}
	return { runIds, failedRunIds };
}

// Modes the `--mode` operator override accepts. Anything else — a typo, a stale
// flag in a script — is rejected loudly rather than silently landing in
// evaluateVerdict's score-headroom branch, which is exactly the class of "config
// that quietly does not do what it says" that #111 exists to remove.
export const QUALIFICATION_MODES = ["score-headroom", "decoy-rate"];

// Modes a MANIFEST may select — deliberately narrower. #111 demoted decoy-rate to
// an informational statistic, so a scenario author must not be able to re-promote
// it to a gating verdict by editing scenario.toml, with no operator involved.
// decoy-rate remains reachable, but only as a deliberate `--mode` override.
export const MANIFEST_QUALIFICATION_MODES = ["score-headroom"];

// Accept either a scenario directory or a direct path to its scenario.toml.
export function resolveScenarioDir(scenarioPath) {
	const p = resolve(scenarioPath);
	return p.endsWith("scenario.toml") ? dirname(p) : p;
}

export function readScenarioMode(scenarioPath) {
	if (!scenarioPath) return "score-headroom";
	const targetPath = join(resolveScenarioDir(scenarioPath), "scenario.toml");
	if (!existsSync(targetPath)) {
		loud(
			`WARNING: scenario manifest not found at ${targetPath}, falling back to score-headroom`,
		);
		return "score-headroom";
	}
	const content = readFileSync(targetPath, "utf8");
	// Section-scoped, matching how tools/rules-lint/lint.mjs reads this manifest:
	// isolate the [verify] block first, then look inside it. A bare file-wide
	// match would pick up a `qualification_mode` sitting under any other section.
	// NOTE: deliberately no `m` flag. With `m`, `$` matches at every line end and
	// the lazy capture terminates after the first line of the block — silently
	// hiding every field below it. `(?:^|\n)` gives the start-of-line anchor
	// instead, and `$` stays end-of-string.
	const verifyBlock = content.match(
		/(?:^|\n)\[verify\][^\n]*\n([\s\S]*?)(?=\n\[|$)/,
	)?.[1];
	const match = verifyBlock?.match(
		/^\s*qualification[_-]mode\s*=\s*["']([^"']+)["']/m,
	);
	if (match?.[1]) {
		const mode = match[1];
		if (!MANIFEST_QUALIFICATION_MODES.includes(mode)) {
			loud(
				mode === "decoy-rate"
					? `WARNING: qualification_mode "decoy-rate" in ${targetPath} is not gating (#111 demoted it to an informational statistic); falling back to score-headroom. Pass --mode decoy-rate explicitly for a legacy scoring.`
					: `WARNING: unknown qualification_mode "${mode}" in ${targetPath} (a manifest may only declare ${MANIFEST_QUALIFICATION_MODES.join(", ")}), falling back to score-headroom`,
			);
			return "score-headroom";
		}
		return mode;
	}
	loud(
		`WARNING: qualification_mode field missing in ${targetPath}, falling back to score-headroom`,
	);
	return "score-headroom";
}

export function parseArgs(argv) {
	const o = {
		cmd: null,
		scenario: null,
		runs: 3,
		useCase: "booklogr",
		agentCmd: null,
		idPrefix: "headroom",
		runIds: [],
		driver: null,
		judge: false,
		threshold: 0.8,
		mode: null,
		date: null,
	};

	if (argv.length > 0) o.cmd = argv[0];

	for (let i = 1; i < argv.length; i++) {
		const a = argv[i];
		if (a === "--scenario") o.scenario = argv[++i];
		else if (a === "--runs") o.runs = parseInt(argv[++i], 10);
		else if (a === "--use-case") o.useCase = argv[++i];
		else if (a === "--agent-cmd") o.agentCmd = argv[++i];
		else if (a === "--id-prefix") o.idPrefix = argv[++i];
		else if (a === "--run-ids")
			o.runIds = argv[++i].split(",").map((s) => s.trim());
		else if (a === "--driver") o.driver = argv[++i];
		else if (a === "--judge") o.judge = true;
		else if (a === "--threshold") o.threshold = parseFloat(argv[++i]);
		else if (a === "--mode") {
			const m = argv[++i];
			if (!QUALIFICATION_MODES.includes(m))
				fail(
					`unknown --mode "${m}" (expected one of ${QUALIFICATION_MODES.join(", ")})`,
				);
			o.mode = m;
		}
		else if (a === "--date") o.date = argv[++i];
		else fail(`unknown flag: ${a}`);
	}
	return o;
}

export async function scoreSubcommand(opts, finderFn = findRecordAndDiagnosis) {
	if (!opts.scenario) fail("--scenario <id> is required");
	if (!opts.runIds || opts.runIds.length === 0)
		fail("--run-ids <rid1,rid2,...> is required");
	// Normalize once: `--scenario` may name the scenario directory or its
	// scenario.toml. Every consumer below (record lookup, verify/ output path)
	// wants the directory, so collapse the two spellings here rather than
	// leaving each call site to guess.
	const scenarioPath = resolveScenarioDir(opts.scenario);
	const useCaseMatch = scenarioPath.match(/use-cases\/([^/]+)/);
	const useCase = opts.useCase || (useCaseMatch ? useCaseMatch[1] : "booklogr");
	const scenarioShort = basename(scenarioPath);

	const rows = [];
	const mitigationScores = [];
	const diagnosisScores = [];
	const diagnoses = [];
	let fallbackDate = new Date().toISOString().split("T")[0];
	let judgeModel = null;

	for (const rid of opts.runIds) {
		const isFailed = opts.failedRunIds && opts.failedRunIds.includes(rid);
		let record, diagnosis, runDir;

		if (isFailed) {
			record = { run_failed: true };
		} else {
			const found = finderFn(useCase, scenarioShort, rid);
			record = found.record;
			diagnosis = found.diagnosis;
			runDir = found.runDir;

			if (!record) {
				const expectedPath = join(
					resolve(REPO_ROOT, "use-cases", useCase),
					"scenarios",
					scenarioShort,
					"records",
					`${rid}.json`,
				);
				fail(`Missing record for run ${rid} at ${expectedPath}`);
			}
		}

		let currentDiagnosis = diagnosis;
		if (opts.judge && runDir) {
			loud(`Invoking rca-judge for run ${rid}...`);
			const judgeRes = spawnSync(
				process.execPath,
				[
					resolve(REPO_ROOT, "tools/rca-judge/judge.mjs"),
					"--judge",
					"--run-dir",
					runDir,
					"--scenario",
					scenarioPath,
				],
				{ stdio: "inherit", env: process.env },
			);
			if (judgeRes.status === 0) {
				const dp = join(runDir, "diagnosis.json");
				if (existsSync(dp)) {
					try {
						currentDiagnosis = JSON.parse(readFileSync(dp, "utf8"));
					} catch {}
				}
			}
		}

		if (
			record.run_failed ||
			record.verdict === "run_failed" ||
			(record.score && record.score.score === undefined && !record.verdict)
		) {
			rows.push({
				runId: rid,
				failed: true,
				mitigationScore: null,
				verdict: "run_failed",
				diagnosisScore: null,
				falseLeads: null,
			});
			continue;
		}

		let mScore = null;
		if (record.score && typeof record.score.score === "number")
			mScore = record.score.score;

		if (mScore !== null) mitigationScores.push(mScore);

		let dScore = null;
		let falseLeads = null;
		if (currentDiagnosis) {
			if (typeof currentDiagnosis.score === "number") {
				dScore = currentDiagnosis.score;
				diagnosisScores.push(dScore);
			}
			if (
				currentDiagnosis.axes &&
				currentDiagnosis.axes.false_leads !== undefined
			) {
				falseLeads = currentDiagnosis.axes.false_leads;
			}
			diagnoses.push(currentDiagnosis);
			if (currentDiagnosis.judge_model && !judgeModel) {
				judgeModel = currentDiagnosis.judge_model;
			}
		} else {
			diagnoses.push(null);
		}

		if (record.timestamp && !opts.date) {
			fallbackDate = record.timestamp;
		}

		rows.push({
			runId: rid,
			failed: false,
			mitigationScore: mScore,
			verdict: record.verdict || "UNKNOWN",
			diagnosisScore: dScore,
			falseLeads: falseLeads,
		});
	}

	const mitigationMedian = computeMedian(mitigationScores);
	const diagnosisMedian = computeMedian(diagnosisScores);
	const decoyRate = computeDecoyRate(diagnoses);

	const effectiveMode = opts.mode || readScenarioMode(scenarioPath);

	const { verdict, reason } = evaluateVerdict({
		mitigationMedian,
		decoyRate,
		mode: effectiveMode,
		threshold: opts.threshold,
	});

	const finalDate = opts.date || fallbackDate;

	const md = generateHeadroomMd({
		date: finalDate,
		driver: opts.driver,
		judgeModel,
		threshold: opts.threshold,
		mode: effectiveMode,
		verdict,
		reason,
		rows,
		mitigationMedian,
		diagnosisMedian,
		decoyRate,
	});

	const scenarioVerify = join(scenarioPath, "verify");
	if (!existsSync(scenarioVerify))
		mkdirSync(scenarioVerify, { recursive: true });
	writeFileSync(join(scenarioVerify, "headroom.md"), md, "utf8");
	loud(`Wrote verify/headroom.md for scenario ${scenarioShort} (${verdict})`);
}

async function main() {
	const opts = parseArgs(process.argv.slice(2));

	if (opts.cmd === "run") {
		if (!opts.scenario) fail("--scenario <id> is required for run");
		const { runIds, failedRunIds } = runCampaign({
			scenario: opts.scenario,
			runs: opts.runs,
			useCase: opts.useCase,
			agentCmd: opts.agentCmd,
			idPrefix: opts.idPrefix,
			executor: defaultExecutor,
		});
		opts.runIds = runIds;
		opts.failedRunIds = failedRunIds;
		await scoreSubcommand(opts);
	} else if (opts.cmd === "score") {
		await scoreSubcommand(opts);
	} else {
		fail(`unknown subcommand: ${opts.cmd}. Use run or score.`);
	}
}

if (
	process.argv[1] &&
	import.meta.url === pathToFileURL(process.argv[1]).href
) {
	main().catch((err) => {
		if (err instanceof HeadroomError) {
			loud(err.message);
			process.exit(2);
		} else {
			loud(`unhandled: ${err.message}`);
			process.exit(2);
		}
	});
}
