#!/usr/bin/env node
// =============================================================================
// generate.mjs — emit the PUBLIC scenario catalog page from scenario manifests.
//
// Issue #98, deliverable 1. Same offline, zero-dependency lint culture as
// tools/rules-lint and tools/record-lint: no install required, runs in CI as a
// staleness gate (`--check`), and the committed output is the artifact.
//
// ---------------------------------------------------------------------------
// LEAKAGE BOUNDARY — the load-bearing constraint
// ---------------------------------------------------------------------------
// The page ships to https://sreforge.sfun.cloud. It may contain ONLY:
//   scenario id, use-case, stack, profile, the qualification status WORD, and a
//   derived role label.
// It must NEVER contain medians, thresholds, scores, or any other number out of
// verify/headroom.md; nor anything from verify/oracle.md, solution/, or inject/;
// nor root-cause or fix wording.
//
// That is enforced STRUCTURALLY, not by review:
//   1. Only two files are ever opened per scenario — scenario.toml and
//      verify/headroom.md. oracle.md, solution/ and inject/ are never read, so
//      their content cannot reach the page even by accident.
//   2. From scenario.toml only the four allowlisted identity keys are read
//      (IDENTITY_FIELDS), scoped to the pre-section preamble. `title` and
//      `description` are deliberately NOT read: on the current corpus both
//      encode the authored root cause ("...dropped a composite index...",
//      "Cache outage masked by an unrelated recent deploy"), which is exactly
//      the "root-cause or fix wording" the boundary forbids. The page therefore
//      carries no free text out of any manifest at all.
//   3. From headroom.md only a single enum token is extracted — QUALIFIED or
//      DISQUALIFIED. No other byte of that file is ever carried forward, so no
//      median, threshold, run id or date can ride along.
//   4. Every allowlisted value is re-validated against a strict token SHAPE
//      (SAFE_TOKEN) before it is rendered: identifier characters only, so any
//      value carrying whitespace, a markdown pipe, an angle bracket or any
//      other punctuation — i.e. anything prose-shaped, or anything that could
//      break out of a table cell — fails the build loudly instead of being
//      published. Note it does NOT reject digits; a numeric-looking identifier
//      would pass. The page's freedom from private numbers comes from (2) and
//      (3) — which fields are read at all — and is pinned by the committed-page
//      test asserting the rendered page contains no digit whatsoever.
//
// Usage:
//   node tools/catalog/generate.mjs            # regenerate the committed page
//   node tools/catalog/generate.mjs --check    # fail if the committed page is stale
// Exit 0 = clean; 1 = drift (--check); 2 = a manifest violated the boundary.
// =============================================================================
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(__dirname, "../..");

export const OUTPUT_RELPATH = "docs/src/content/docs/reference/scenario-catalog.md";
export const GITHUB_TREE_BASE = "https://github.com/prismalens/sreforge/tree/main/use-cases";
export const BANNER = "<!-- GENERATED by tools/catalog/generate.mjs — edit the generator, not this file. -->";

// The complete set of manifest keys this generator is permitted to read. Adding
// to this list widens the public surface — do not do it without re-reading the
// leakage boundary above.
export const IDENTITY_FIELDS = ["id", "use_case", "stack", "profile"];

// Profiles the taxonomy defines. An unknown profile is a hard error rather than
// a passthrough, so a typo (or free text) can never reach the page.
export const PROFILES = ["incident", "patch"];

// Identifier SHAPE only: letters, digits, dot, underscore, hyphen. This rejects
// whitespace, markdown pipes, angle brackets and every other punctuation mark —
// so no prose and no cell-breaking or HTML-injecting value can be rendered.
// It deliberately does NOT reject digits (a numeric-looking id is a legitimate
// identifier); keeping private numbers off the page is the job of the field
// allowlist above, not of this pattern.
const SAFE_TOKEN = /^[a-z0-9][a-z0-9._-]*$/i;

export const ROLE_BY_STATUS = {
	DISQUALIFIED: "regression-guard / CI-smoke",
	QUALIFIED: "certification-substrate",
};
export const NO_HEADROOM_STATUS = "unqualified (no headroom run)";
export const NO_HEADROOM_ROLE = "pending qualification";

// --- manifest reading --------------------------------------------------------

/**
 * Isolate the pre-section preamble of a scenario.toml — everything before the
 * first `[section]` header. Identity keys live there; `stack` also appears later
 * under a paths section as a relative path, and a file-wide match would pick up
 * the wrong one. Same section-scoping discipline as tools/rules-lint/lint.mjs
 * and tools/headroom/campaign.mjs, and the same reason: a naive match on this
 * manifest silently reads the wrong block.
 * @param {string} content
 * @returns {string}
 */
export function identityBlock(content) {
	const out = [];
	for (const line of content.split(/\r?\n/)) {
		if (/^\s*\[/.test(line)) break;
		out.push(line);
	}
	return out.join("\n");
}

/**
 * Read one quoted scalar out of a TOML block. Only quoted values are accepted,
 * which sidesteps trailing `# BINDING — ...` comments entirely.
 * @param {string} block
 * @param {string} key
 * @returns {string|null}
 */
export function readQuotedField(block, key) {
	const m = block.match(new RegExp(`^\\s*${key}\\s*=\\s*["']([^"'\\n]*)["']`, "m"));
	return m ? m[1] : null;
}

/**
 * Extract exactly the allowlisted identity fields from a scenario.toml.
 * @param {string} content
 * @param {string} where - path, for error messages
 * @returns {{id: string, use_case: string, stack: string, profile: string}}
 */
export function readIdentity(content, where = "scenario.toml") {
	const block = identityBlock(content);
	const out = {};
	for (const key of IDENTITY_FIELDS) {
		const value = readQuotedField(block, key);
		if (value === null) {
			throw new Error(`${where}: required identity field '${key}' is missing from the manifest preamble`);
		}
		if (!SAFE_TOKEN.test(value)) {
			throw new Error(
				`${where}: identity field '${key}' = ${JSON.stringify(value)} is not a bare identifier. ` +
					`The public catalog only publishes identifier-shaped values (leakage boundary).`,
			);
		}
		out[key] = value;
	}
	if (!PROFILES.includes(out.profile)) {
		throw new Error(`${where}: unknown profile ${JSON.stringify(out.profile)} (expected one of ${PROFILES.join(", ")})`);
	}
	return out;
}

/**
 * Extract ONLY the qualification verdict word from a headroom report — the first
 * bold QUALIFIED/DISQUALIFIED token in the file. Nothing else from this file is
 * ever read forward: the medians, thresholds, per-run scores and run ids in it
 * are private baseline data.
 * @param {string} content
 * @returns {"QUALIFIED"|"DISQUALIFIED"|null}
 */
export function readVerdict(content) {
	const m = content.match(/\*\*(DISQUALIFIED|QUALIFIED)\*\*/);
	return m ? /** @type {"QUALIFIED"|"DISQUALIFIED"} */ (m[1]) : null;
}

// --- row assembly ------------------------------------------------------------

/**
 * @param {"QUALIFIED"|"DISQUALIFIED"|null} verdict
 * @returns {{status: string, role: string}}
 */
export function classify(verdict) {
	if (verdict === null) return { status: NO_HEADROOM_STATUS, role: NO_HEADROOM_ROLE };
	return { status: verdict, role: ROLE_BY_STATUS[verdict] };
}

/**
 * Walk use-cases/<uc>/scenarios/<id>/ and build one row per scenario.
 * @param {string} root - repo root to scan
 * @returns {Array<{id: string, useCase: string, stack: string, profile: string, status: string, role: string}>}
 */
export function collectScenarios(root = REPO_ROOT) {
	const useCasesDir = join(root, "use-cases");
	if (!existsSync(useCasesDir)) return [];
	const rows = [];

	for (const uc of readdirSync(useCasesDir, { withFileTypes: true })) {
		if (!uc.isDirectory()) continue;
		const scenariosDir = join(useCasesDir, uc.name, "scenarios");
		if (!existsSync(scenariosDir)) continue;

		for (const sc of readdirSync(scenariosDir, { withFileTypes: true })) {
			if (!sc.isDirectory()) continue;
			const manifestPath = join(scenariosDir, sc.name, "scenario.toml");
			if (!existsSync(manifestPath)) continue;

			const identity = readIdentity(readFileSync(manifestPath, "utf8"), manifestPath);

			// The directory name is the scenario id of record (rules-lint and the
			// runner both key off it). A manifest that disagrees is a real defect.
			if (identity.id !== sc.name) {
				throw new Error(`${manifestPath}: id ${JSON.stringify(identity.id)} does not match its directory name ${JSON.stringify(sc.name)}`);
			}
			if (identity.use_case !== uc.name) {
				throw new Error(`${manifestPath}: use_case ${JSON.stringify(identity.use_case)} does not match its use-case directory ${JSON.stringify(uc.name)}`);
			}

			// The ONLY other file this generator opens. oracle.md, solution/ and
			// inject/ are never touched.
			const headroomPath = join(scenariosDir, sc.name, "verify", "headroom.md");
			const verdict = existsSync(headroomPath) ? readVerdict(readFileSync(headroomPath, "utf8")) : null;

			rows.push({
				id: identity.id,
				useCase: identity.use_case,
				stack: identity.stack,
				profile: identity.profile,
				...classify(verdict),
			});
		}
	}

	// Code-unit ordering, NOT locale collation. The rendered page is compared
	// byte-for-byte by --check, so the row order must be identical on every
	// runtime. localeCompare depends on the ambient locale and the ICU data the
	// node build ships with, and it disagrees with code-unit order on exactly the
	// characters scenario ids use: it sorts ["ab","a-b","a_b"] as a_b, a-b, ab
	// while code-unit order is a-b, a_b, ab. That difference would make
	// catalog:check flap between a developer's machine and CI.
	const byCodeUnit = (x, y) => (x < y ? -1 : x > y ? 1 : 0);
	rows.sort((a, b) => byCodeUnit(a.useCase, b.useCase) || byCodeUnit(a.id, b.id));
	return rows;
}

// --- rendering ---------------------------------------------------------------

const FRONTMATTER = [
	"---",
	"title: Scenario catalog",
	"description: The public index of SREForge scenarios — identity, profile, role, and qualification status.",
	"---",
].join("\n");

// NOTE: the banner sits immediately AFTER the frontmatter, not before it.
// Starlight requires the YAML block to be the first bytes of the file; a leading
// HTML comment makes the page frontmatter-less and breaks the docs build.
const INTRO = [
	"A scenario is a reproducible fault, injected into a live use-case stack, paired with a closed-loop check that decides whether an agent actually restored the service.",
	"Scenario identities and the methodology around them are public — that is what this page is; the authored root causes, the oracle rubrics, the per-run records and every score they carry live in a private store and are never published here (locally, per-run detail is rendered by `pnpm runs:dashboard`).",
	"The Role column says what each scenario is for today: most no longer separate frontier models on capability, so they earn their keep as regression guards rather than as discrimination axes.",
].join("\n");

const TABLE_HEADER = ["| Scenario | Use-case | Profile | Role | Status |", "| --- | --- | --- | --- | --- |"];

/**
 * @param {ReturnType<typeof collectScenarios>[number]} row
 * @returns {string}
 */
export function renderRow(row) {
	const link = `[${row.id}](${GITHUB_TREE_BASE}/${row.useCase}/scenarios/${row.id})`;
	return `| ${link} | ${row.useCase} | ${row.profile} | ${row.role} | ${row.status} |`;
}

/**
 * @param {ReturnType<typeof collectScenarios>} rows
 * @returns {string}
 */
export function renderPage(rows) {
	return [FRONTMATTER, "", BANNER, "", INTRO, "", ...TABLE_HEADER, ...rows.map(renderRow), ""].join("\n");
}

/**
 * @param {string} root
 * @returns {string}
 */
export function generate(root = REPO_ROOT) {
	return renderPage(collectScenarios(root));
}

// --- cli ---------------------------------------------------------------------

function main() {
	const check = process.argv.slice(2).includes("--check");
	const outPath = join(REPO_ROOT, OUTPUT_RELPATH);

	let expected;
	try {
		expected = generate(REPO_ROOT);
	} catch (err) {
		console.error(`[catalog] FATAL: ${err.message}`);
		process.exit(2);
	}

	if (check) {
		const actual = existsSync(outPath) ? readFileSync(outPath, "utf8") : null;
		if (actual === expected) {
			console.log(`[catalog] ${OUTPUT_RELPATH} is up to date.`);
			process.exit(0);
		}
		console.error(
			actual === null
				? `[catalog] DRIFT: ${OUTPUT_RELPATH} does not exist.`
				: `[catalog] DRIFT: ${OUTPUT_RELPATH} does not match the scenario manifests.`,
		);
		console.error("[catalog] run pnpm catalog:gen and commit the result.");
		process.exit(1);
	}

	writeFileSync(outPath, expected);
	console.log(`[catalog] wrote ${OUTPUT_RELPATH}`);
	process.exit(0);
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
	main();
}
